dubbo:
  application:
    name: web_class_provider
  registry:
    address: zookeeper://192.168.106.188:2181
  protocol:
    port: -1
spring:
  datasource:
    url: jdbc:mysql:///db_cls?serverTimezone=GMT%2B8
    username: root
    password: 456
    driver-class-name: com.mysql.cj.jdbc.Driver

